import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./client-layout";
import Layoutt from "./Layoutt";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kashish India Api",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/mainlogo.jpg",
        type: "image/x-icon",
      },
      {
        url: "/mainlogo.jpg",
        type: "image/jpg",
        sizes: "16x16",
      },
      {
       url: "/mainlogo.jpg",
        type: "image/jpg",
        sizes: "32x32",
      },
    ],
    apple: {
      url: "/mainlogo.jpg",
      sizes: "180x180",
      type: "image/jpg",
    },
    shortcut: {
      url: "/mainlogo.jpg",
      type: "image/x-icon",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <ClientLayout>
          <Layoutt>
            {children}
          </Layoutt>
        </ClientLayout>
      </body>
    </html>
  );
}
